# Homebrew formula for agent-iap, in the repository it installs:
#
#   brew tap vpetersson/agent-iap https://github.com/vpetersson/agent-iap
#   brew trust vpetersson/agent-iap
#   brew install agent-iap
#
# Generated by scripts/update-formula.sh, which the release workflow runs with
# the checksums of the assets it has just published. Edit the script, not this.
class AgentIap < Formula
  desc "Identity-aware proxy for LLM agents: ACL-gated, audited access to APIs and MCP"
  homepage "https://github.com/vpetersson/agent-iap"
  version "2026.9.0"
  license "MIT"

  # `brew install --HEAD agent-iap` builds master instead, for a fix that is
  # merged but not yet tagged.
  head do
    url "https://github.com/vpetersson/agent-iap.git", branch: "master"
    depends_on "rust" => :build
  end

  # Otherwise the release tarballs, not a build: the binaries are the ones the
  # release tested and checksummed, so nothing is compiled on the way in and
  # there is no toolchain to install first. Linux is static musl — Homebrew's
  # own glibc story does not come into it.
  on_macos do
    on_arm do
      url "https://github.com/vpetersson/agent-iap/releases/download/v2026.9.0/agent-iap-2026.9.0-macos-arm64.tar.gz"
      sha256 "03171323ca633859b36bc0d4e54c0f616ab4ebe5cd7ce05322aeb20232d81870"
    end
    on_intel do
      url "https://github.com/vpetersson/agent-iap/releases/download/v2026.9.0/agent-iap-2026.9.0-macos-x86_64.tar.gz"
      sha256 "d1f64f214c74170124198a8d96a9576faff4cae945c0c777bb4d79c548d62fb6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vpetersson/agent-iap/releases/download/v2026.9.0/agent-iap-2026.9.0-linux-aarch64.tar.gz"
      sha256 "e3604c1e8e88d4c79204b20e5568449bf892fed09fd6dcf3d63e342df89f4ac5"
    end
    on_intel do
      url "https://github.com/vpetersson/agent-iap/releases/download/v2026.9.0/agent-iap-2026.9.0-linux-x86_64.tar.gz"
      sha256 "941053cbe245f93e23838898b12b7ba62a871f8fe5b9c5c69f3efa621c829c2b"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "agent-iap"
      doc.install "README.md"
    end

    # `brew services` starts nothing until these exist, and creating them at
    # install time means the service block below is the only thing that has to
    # agree about where they are.
    (var/"lib/agent-iap").mkpath
    (var/"log").mkpath
  end

  # The daemon, as launchd or systemd sees it — the same shape as
  # packaging/agent-iap.service: no console, so an `ask` rule is answered over
  # the control plane or denied (README.md § Control plane). The environment is
  # spelled out because a service has no working directory worth defaulting
  # from: without `IAP_CONFIG` the proxy would look for an `iap.toml` next to
  # wherever it was started.
  service do
    run [opt_bin/"agent-iap", "run", "--no-tui"]
    keep_alive true
    working_dir var/"lib/agent-iap"
    log_path var/"log/agent-iap.log"
    error_log_path var/"log/agent-iap.log"
    environment_variables IAP_CONFIG:    etc/"agent-iap/iap.toml",
                          IAP_STATE_DIR: var/"lib/agent-iap"
  end

  def caveats
    <<~CAVEATS
      A policy file is the whole configuration, and there is no useful default
      for one — it names the upstreams, the agents and the rules. Write it:

        agent-iap init --config #{etc}/agent-iap/iap.toml
        chmod 0600 #{etc}/agent-iap/iap.toml

      It holds no credential — agent tokens are stored as sha256 and an
      upstream's key is a reference to somewhere else — but readable it is a map
      of every credential worth going after.

      `brew services start agent-iap` then runs the proxy against that file,
      with no approval console: an `ask` rule is answered over the control plane
      or it denies. `agent-iap run` in a terminal is the console.
    CAVEATS
  end

  test do
    assert_match "agent-iap", shell_output("#{bin}/agent-iap --version")

    # The `minimal` template enrols nobody and mints no token, so this prints no
    # secret and never reaches for the clipboard. `check` then reads the file
    # back and resolves every credential reference in it, which is a real pass
    # over the config path with nothing in it to leak.
    system bin/"agent-iap", "init", "--config", testpath/"iap.toml",
           "--template", "minimal", "--no-clipboard"
    assert_path_exists testpath/"iap.toml"
    system bin/"agent-iap", "check", "--config", testpath/"iap.toml"
  end
end
