# Homebrew formula for agent-iap, in the repository it installs:
#
#   brew tap vpetersson/agent-iap https://github.com/vpetersson/agent-iap
#   brew trust vpetersson/agent-iap
#   brew install agent-iap
#
# Generated by scripts/update-formula.sh, which the release workflow runs with
# the checksums of the assets it has just published. Edit the script, not this.
class AgentIap < Formula
  desc "Identity-aware proxy for LLM agents: ACL-gated, audited access to APIs and MCP"
  homepage "https://github.com/vpetersson/agent-iap"
  license "MIT"

  # No `v…` tag has been cut yet, so there is no release asset to pin a
  # sha256 against and nothing for a stable install to download. Until there
  # is, the formula builds master:
  #
  #   brew install --HEAD agent-iap
  #
  # The first release regenerates this file with the binaries in it, and the
  # plain `brew install` starts working with no change to the tap.
  head "https://github.com/vpetersson/agent-iap.git", branch: "master"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args

    (var/"lib/agent-iap").mkpath
    (var/"log").mkpath
  end

  # The daemon, as launchd or systemd sees it — the same shape as
  # packaging/agent-iap.service: no console, so an `ask` rule is answered over
  # the control plane or denied (README.md § Control plane). The environment is
  # spelled out because a service has no working directory worth defaulting
  # from: without `IAP_CONFIG` the proxy would look for an `iap.toml` next to
  # wherever it was started.
  service do
    run [opt_bin/"agent-iap", "run", "--no-tui"]
    keep_alive true
    working_dir var/"lib/agent-iap"
    log_path var/"log/agent-iap.log"
    error_log_path var/"log/agent-iap.log"
    environment_variables IAP_CONFIG:    etc/"agent-iap/iap.toml",
                          IAP_STATE_DIR: var/"lib/agent-iap"
  end

  def caveats
    <<~CAVEATS
      A policy file is the whole configuration, and there is no useful default
      for one — it names the upstreams, the agents and the rules. Write it:

        agent-iap init --config #{etc}/agent-iap/iap.toml
        chmod 0600 #{etc}/agent-iap/iap.toml

      It holds no credential — agent tokens are stored as sha256 and an
      upstream's key is a reference to somewhere else — but readable it is a map
      of every credential worth going after.

      `brew services start agent-iap` then runs the proxy against that file,
      with no approval console: an `ask` rule is answered over the control plane
      or it denies. `agent-iap run` in a terminal is the console.
    CAVEATS
  end

  test do
    assert_match "agent-iap", shell_output("#{bin}/agent-iap --version")

    # The `minimal` template enrols nobody and mints no token, so this prints no
    # secret and never reaches for the clipboard. `check` then reads the file
    # back and resolves every credential reference in it, which is a real pass
    # over the config path with nothing in it to leak.
    system bin/"agent-iap", "init", "--config", testpath/"iap.toml",
           "--template", "minimal", "--no-clipboard"
    assert_path_exists testpath/"iap.toml"
    system bin/"agent-iap", "check", "--config", testpath/"iap.toml"
  end
end
