#!/usr/bin/env bash
# Write Formula/agent-iap.rb, the Homebrew formula that lives in the repository
# it installs (README.md § Install).
#
# The tap is this repo, so there is no second repository to keep in step — but
# there is also nothing to stop the formula drifting from the release it claims
# to install, because a sha256 is not something anyone notices is stale. So it
# is generated rather than edited: the release workflow runs this with the
# checksums of the assets it has just published and commits the result back to
# master.
#
# Run it by hand to recover from a release that failed after uploading, or with
# no version at all to put the formula back to the source build it was before
# the first tag.
#
#   scripts/update-formula.sh                                    # HEAD-only
#   scripts/update-formula.sh v2026.9.1                          # fetch that release's SHA256SUMS
#   scripts/update-formula.sh v2026.9.1 --checksums dist/SHA256SUMS
set -euo pipefail

cd "$(dirname "$0")/.."

repo=vpetersson/agent-iap
formula=Formula/agent-iap.rb

version=
checksums=

die() {
    echo "update-formula: $*" >&2
    exit 1
}

while [ $# -gt 0 ]; do
    case $1 in
        --checksums)
            [ $# -ge 2 ] || die "--checksums needs a file"
            checksums=$2
            shift 2
            ;;
        -h | --help)
            sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        -*)
            die "unknown option \`$1\`"
            ;;
        *)
            [ -z "$version" ] || die "one version, not \`$version\` and \`$1\`"
            version=$1
            shift
            ;;
    esac
done

# `v2026.9.1` and `2026.9.1` both name the same release; the tag carries the
# `v` and the asset names do not, so accept either and keep them apart here.
version=${version#v}

if [ -z "$version" ]; then
    [ -z "$checksums" ] || die "--checksums without a version — which release are they for?"
else
    # The same shape check-version.sh enforces on Cargo.toml. A version this
    # rejects has no release to point the formula at anyway.
    [[ $version =~ ^[0-9]{4}\.[0-9]{1,2}\.[0-9]+$ ]] ||
        die "\`$version\` is not CalVer — expected YYYY.MM.PATCH, e.g. 2026.9.1"
fi

# Reading them out of the published SHA256SUMS rather than hashing downloaded
# tarballs keeps this to one request and checks the formula against the same
# file a human is told to verify with.
if [ -n "$version" ] && [ -z "$checksums" ]; then
    checksums=$(mktemp)
    trap 'rm -f "$checksums"' EXIT
    url="https://github.com/$repo/releases/download/v$version/SHA256SUMS"
    curl -sSfL "$url" -o "$checksums" || die "no SHA256SUMS at $url"
fi

# `sha256sum` writes `<hash>  <name>` and `shasum -a 256` can write `<hash>
# *<name>`; a path creeps in when the file was generated from another
# directory. Match on the base name and take the hash.
sum_for() {
    local want="agent-iap-$version-$1.tar.gz" sum
    sum=$(
        awk -v want="$want" '
            {
                name = $NF
                sub(/^\*/, "", name)
                sub(/.*\//, "", name)
                if (name == want) { print $1; exit }
            }
        ' "$checksums"
    )
    [ -n "$sum" ] || die "no checksum for $want in $checksums"
    [[ $sum =~ ^[0-9a-f]{64}$ ]] || die "checksum for $want is not a sha256: \`$sum\`"
    printf '%s' "$sum"
}

# The four assets .github/workflows/release.yml builds, under the names
# Homebrew calls the platforms.
platform_block() {
    local indent=$1 asset=$2
    cat <<EOF
$indent  url "https://github.com/$repo/releases/download/v$version/agent-iap-$version-$asset.tar.gz"
$indent  sha256 "$(sum_for "$asset")"
EOF
}

mkdir -p "$(dirname "$formula")"
tmp=$(mktemp)

{
    cat <<'EOF'
# Homebrew formula for agent-iap, in the repository it installs:
#
#   brew tap vpetersson/agent-iap https://github.com/vpetersson/agent-iap
#   brew trust vpetersson/agent-iap
#   brew install agent-iap
#
# Generated by scripts/update-formula.sh, which the release workflow runs with
# the checksums of the assets it has just published. Edit the script, not this.
class AgentIap < Formula
  desc "Identity-aware proxy for LLM agents: ACL-gated, audited access to APIs and MCP"
  homepage "https://github.com/vpetersson/agent-iap"
EOF

    if [ -n "$version" ]; then
        # \`brew audit --strict\` calls the version stanza redundant because it
        # can also read one out of the URLs. It is written anyway: that reader
        # is a heuristic, and on a name ending \`-linux-x86_64.tar.gz\` it has
        # been seen to pick \`86.64\` out of the architecture. The order of the
        # stanzas is the one \`brew style\` enforces — version before license,
        # \`head\` before the platform blocks.
        cat <<EOF
  version "$version"
  license "MIT"

  # \`brew install --HEAD agent-iap\` builds master instead, for a fix that is
  # merged but not yet tagged.
  head do
    url "https://github.com/$repo.git", branch: "master"
    depends_on "rust" => :build
  end

  # Otherwise the release tarballs, not a build: the binaries are the ones the
  # release tested and checksummed, so nothing is compiled on the way in and
  # there is no toolchain to install first. Linux is static musl — Homebrew's
  # own glibc story does not come into it.
  on_macos do
    on_arm do
$(platform_block "    " macos-arm64)
    end
    on_intel do
$(platform_block "    " macos-x86_64)
    end
  end

  on_linux do
    on_arm do
$(platform_block "    " linux-aarch64)
    end
    on_intel do
$(platform_block "    " linux-x86_64)
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "agent-iap"
      doc.install "README.md"
    end

    # \`brew services\` starts nothing until these exist, and creating them at
    # install time means the service block below is the only thing that has to
    # agree about where they are.
    (var/"lib/agent-iap").mkpath
    (var/"log").mkpath
  end
EOF
    else
        cat <<EOF
  license "MIT"

  # No \`v…\` tag has been cut yet, so there is no release asset to pin a
  # sha256 against and nothing for a stable install to download. Until there
  # is, the formula builds master:
  #
  #   brew install --HEAD agent-iap
  #
  # The first release regenerates this file with the binaries in it, and the
  # plain \`brew install\` starts working with no change to the tap.
  head "https://github.com/$repo.git", branch: "master"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args

    (var/"lib/agent-iap").mkpath
    (var/"log").mkpath
  end
EOF
    fi

    cat <<'EOF'

  # The daemon, as launchd or systemd sees it — the same shape as
  # packaging/agent-iap.service: no console, so an `ask` rule is answered over
  # the control plane or denied (README.md § Control plane). The environment is
  # spelled out because a service has no working directory worth defaulting
  # from: without `IAP_CONFIG` the proxy would look for an `iap.toml` next to
  # wherever it was started.
  service do
    run [opt_bin/"agent-iap", "run", "--no-tui"]
    keep_alive true
    working_dir var/"lib/agent-iap"
    log_path var/"log/agent-iap.log"
    error_log_path var/"log/agent-iap.log"
    environment_variables IAP_CONFIG:    etc/"agent-iap/iap.toml",
                          IAP_STATE_DIR: var/"lib/agent-iap"
  end

  def caveats
    <<~CAVEATS
      A policy file is the whole configuration, and there is no useful default
      for one — it names the upstreams, the agents and the rules. Write it:

        agent-iap init --config #{etc}/agent-iap/iap.toml
        chmod 0600 #{etc}/agent-iap/iap.toml

      It holds no credential — agent tokens are stored as sha256 and an
      upstream's key is a reference to somewhere else — but readable it is a map
      of every credential worth going after.

      `brew services start agent-iap` then runs the proxy against that file,
      with no approval console: an `ask` rule is answered over the control plane
      or it denies. `agent-iap run` in a terminal is the console.
    CAVEATS
  end

  test do
    assert_match "agent-iap", shell_output("#{bin}/agent-iap --version")

    # The `minimal` template enrols nobody and mints no token, so this prints no
    # secret and never reaches for the clipboard. `check` then reads the file
    # back and resolves every credential reference in it, which is a real pass
    # over the config path with nothing in it to leak.
    system bin/"agent-iap", "init", "--config", testpath/"iap.toml",
           "--template", "minimal", "--no-clipboard"
    assert_path_exists testpath/"iap.toml"
    system bin/"agent-iap", "check", "--config", testpath/"iap.toml"
  end
end
EOF
} > "$tmp"

mv "$tmp" "$formula"
chmod 0644 "$formula"

if [ -n "$version" ]; then
    echo "update-formula: $formula → $version, four platforms."
else
    echo "update-formula: $formula → HEAD only, no release pinned."
fi
